/* Thailand Trip App — curated content & app hub data */
window.TH_DATA = {
  thbToIls: 0.11,
  storageKey: 'thailand-trip-app-v1',

  interests: [
    { id: 'beaches', he: 'חופים', icon: '🏖️' },
    { id: 'islands', he: 'איים', icon: '🏝️' },
    { id: 'culture', he: 'תרבות ומקדשים', icon: '🛕' },
    { id: 'food', he: 'אוכל', icon: '🍜' },
    { id: 'nightlife', he: 'חיי לילה', icon: '🎉' },
    { id: 'nature', he: 'טבע וג׳ונגל', icon: '🌿' },
    { id: 'adventure', he: 'הרפתקאות', icon: '🧗' },
    { id: 'wellness', he: 'וולנס / ספא', icon: '🧘' },
    { id: 'markets', he: 'שווקים', icon: '🛒' },
    { id: 'nomad', he: 'נוודים דיגיטליים', icon: '💻' },
    { id: 'family', he: 'משפחות', icon: '👨‍👩‍👧‍👦' },
    { id: 'lgbtq', he: 'ידידותי ל־LGBTQ+', icon: '🏳️‍🌈' },
    { id: 'photo', he: 'צילום', icon: '📸' }
  ],

  regions: [
    {
      id: 'bangkok', name: 'Bangkok', he: 'בנגקוק', emoji: '🏙️',
      vibe: ['עיר', 'אוכל', 'לילה', 'קניות'], interests: ['food','culture','nightlife','markets','nomad','lgbtq','photo'],
      bestFor: 'אוכל רחוב ברמה עולמית, מקדשים, רובעים כמו Ari / Thonglor / Chinatown, בסיס לטיסות פנימיות',
      bestMonths: 'נוב–פבר (קריר יחסית). מר–מאי חם מאוד. יוני–אוק גשם אחר הצהריים',
      budget: { low: 1200, mid: 2500, high: 5000 },
      mustDos: ['רחוב אוכל ב־Yaowarat (צ׳יינהטאון) בלילה', 'מקדש Wat Arun בשקיעה + חציית הנהר', 'שוק צף / Chatuchak בסופ״ש', 'שכונת Ari — קפה, ברים, ויב מקומי', 'מסאג׳ תאי מסורתי באזור Khao San / Sukhumvit'],
      skipIf: 'אתם שונאים ערים עמוסות וחום — עברו מהר לצפון או לאיים',
      transit: 'BTS/MRT + Grab. משדה Suvarnabhumi: Airport Rail Link. Don Mueang לטיסות זולות.',
      food: 'Pad Thai ב־Thip Samai, boat noodles, mango sticky rice, som tum, moo ping. נסו גם איזור Ari ו־Charoenkrung.'
    },
    {
      id: 'chiangmai', name: 'Chiang Mai', he: 'צ׳יאנג מאי / צפון', emoji: '⛰️',
      vibe: ['תרבות', 'טבע', 'נוודים', 'קפה'], interests: ['culture','food','nature','wellness','nomad','markets','photo','adventure'],
      bestFor: 'מקדשים בעיר העתיקה, הרים, קפה ספשלטי, קצב רגוע, קהילת נוודים',
      bestMonths: 'נוב–פבר מושלם. מר–אפר עונת שריפות (איכות אוויר גרועה!). מאי–אוק גשם ירוק',
      budget: { low: 900, mid: 1800, high: 3500 },
      mustDos: ['Old Town — חומת לבנים + Wat Phra Singh', 'Doi Suthep בשעת זהב', 'Sunday Walking Street', 'יום טרקים / אתיקה עם פילים (לא רכיבה!)', 'קפה ב־Nimman / Santitham'],
      skipIf: 'מרץ–אפריל בגלל עשן — אל תתעלמו מאזהרות AQI',
      transit: 'טיסה מבנגקוק ~1ש. רכבת לילית רומנטית אבל איטית. בתוך העיר: Grab / songthaew אדום.',
      food: 'Khao soi (חובה!), sai ua, nam prik ong, Northern curry. שוק Warorot בבוקר.'
    },
    {
      id: 'chiangrai', name: 'Chiang Rai', he: 'צ׳יאנג ראי', emoji: '🏛️',
      vibe: ['תרבות', 'גבול', 'טבע'], interests: ['culture','photo','nature','adventure'],
      bestFor: 'White Temple, Blue Temple, משולש הזהב, אווירה פחות תיירותית מ־CM',
      bestMonths: 'נוב–פבר. אותה בעיית עשן באביב כמו בצפון',
      budget: { low: 800, mid: 1600, high: 3000 },
      mustDos: ['Wat Rong Khun (White Temple)', 'Wat Rong Suea Ten (Blue Temple)', 'Golden Triangle viewpoint', 'לילה ב־Chiang Rai town או בכפרים סביב'],
      skipIf: 'אין לכם לפחות יומיים — יום אחד ממהר מדי מה־CM',
      transit: 'אוטובוס/מיניוואן מ־Chiang Mai ~3–3.5ש. שדה תעופה מקומי.',
      food: 'אוכל צפוני + השפעות לאו/מיאנמר בגבול. נסו חנויות אטריות מקומיות.'
    },
    {
      id: 'pai', name: 'Pai', he: 'פאי', emoji: '🌄',
      vibe: ['היפי', 'טבע', 'רגוע'], interests: ['nature','wellness','nightlife','photo','adventure'],
      bestFor: 'ויב בוהמייני, מפלים, קניונים, ברים לאורך הנהר, ספא זול',
      bestMonths: 'נוב–פבר. גשם הופך כבישים לבוציים',
      budget: { low: 700, mid: 1400, high: 2800 },
      mustDos: ['Pai Canyon בשקיעה', 'מפלים (Pam Bok / Mo Paeng)', 'שוק לילה + Live music', 'ספא / יוגה זולים'],
      skipIf: 'אתם רגישים לעיקולי כביש — הדרך מ־CM מפורסמת בבחילות',
      transit: 'מיניוואן מ־Chiang Mai ~3–4ש על כביש מפותל. סקוטר בעיר (זהירות!).',
      food: 'מיקס תאי־מערבי להיפים. שייקים, אוכל טבעוני, ברבקיו ברחוב.'
    },
    {
      id: 'phuket', name: 'Phuket', he: 'פוקט', emoji: '🌴',
      vibe: ['חופים', 'מסיבות', 'נוחות'], interests: ['beaches','islands','nightlife','food','family','wellness','photo'],
      bestFor: 'תשתית תיירותית מלאה, טיסות ישירות, בחירה בין פארטי (Patong) לרגוע (Kata/Karon/Nai Harn)',
      bestMonths: 'נוב–אפר. מאי–אוק גלים חזקים בצד המערבי',
      budget: { low: 1500, mid: 3000, high: 7000 },
      mustDos: ['בחרו חוף לפי ויב: Kata/Karon למשפחות, Nai Harn/Freedom לרגוע', 'Old Phuket Town — רחובות סינו-פורטוגזיים', 'טיול יום ל־Phi Phi או James Bond Island (קרבי)', 'שוק לילה / אוכל ב־Phuket Town'],
      skipIf: 'Patong אם אתם מחפשים שקט — זה רועש, דחוס ומסחרי',
      transit: 'שדה בינלאומי. Grab בכל האי. מעבורות מ־Rassada / Ratsada pier.',
      food: 'מטבח דרום־תאי חריף, פירות ים ב־Rawai, מוקפצים ב־Phuket Town.'
    },
    {
      id: 'krabi', name: 'Krabi', he: 'קרבי', emoji: '🏞️',
      vibe: ['טבע', 'חופים', 'הרפתקה'], interests: ['beaches','nature','adventure','photo','islands'],
      bestFor: 'צוקים, מערות, Ao Nang כבסיס, גישה ל־Railay ו־4 Islands',
      bestMonths: 'נוב–אפר. בעונת גשם חלק מהאיים פחות נגישים',
      budget: { low: 1200, mid: 2400, high: 4500 },
      mustDos: ['4 Islands tour (Chicken, Tup, Poda…)', 'טיול ל־Hong Island', 'Tiger Cave Temple (1237 מדרגות!)', 'שקיעה ב־Ao Nang'],
      skipIf: 'אתם רוצים מסיבות גדולות — לכו לפוקט/פנגן',
      transit: 'טיסה ל־Krabi Airport. מ־Ao Nang לונגטייל ל־Railay ~15 דק׳.',
      food: 'פירות ים טריים, massaman, אוכל רחוב ב־Ao Nang night market.'
    },
    {
      id: 'railay', name: 'Railay', he: 'ריילי', emoji: '🧗',
      vibe: ['דרמטי', 'טיפוס', 'חוף'], interests: ['beaches','adventure','photo','wellness'],
      bestFor: 'גישה רק בסירה, צוקי ליים־סטון, Phra Nang Cave Beach — אחד החופים היפים בתאילנד',
      bestMonths: 'נוב–אפר',
      budget: { low: 1500, mid: 2800, high: 5500 },
      mustDos: ['Phra Nang Beach + מערת הפאלים', 'טיפוס צוקים (אפילו שיעור למתחילים)', 'Viewpoint לזריחה', 'West Railay בשקיעה'],
      skipIf: 'תקציב מאוד נמוך — הכל יקר יותר כי אין כביש',
      transit: 'לונגטייל מ־Ao Nang או מ־Ferry pier. אין מכוניות באי.',
      food: 'מסעדות נוף יקרות יחסית. ארוחת בוקר עם נוף צוקים שווה.'
    },
    {
      id: 'phiphi', name: 'Phi Phi', he: 'פי פי', emoji: '⛵',
      vibe: ['אייקוני', 'מסיבות', 'צפוף'], interests: ['beaches','islands','nightlife','photo','adventure'],
      bestFor: 'Maya Bay (עם מגבלות), צלילה/סנורקל, ויב מסיבה ב־Tonsai',
      bestMonths: 'נוב–אפר. עונת גשם — מעבורות מתבטלות',
      budget: { low: 1400, mid: 2800, high: 5000 },
      mustDos: ['סנורקל / צלילה סביב האי', 'Viewpoint מזרח־מערב', 'Long Beach לשקט יחסי', 'Maya Bay — בדקו כללים נוכחיים'],
      skipIf: 'אתם שונאים המונים — Tonsai צפוף מאוד ביום',
      transit: 'מעבורת מפוקט (~2ש) או קרבי. הזמינו דרך 12Go / דוכן בנמל.',
      food: 'פירות ים על החוף, מחירים תיירותיים. מים יקרים — הביאו בקבוק.'
    },
    {
      id: 'samui', name: 'Koh Samui', he: 'קו סמוי', emoji: '🥥',
      vibe: ['נוחות', 'חופים', 'משפחות'], interests: ['beaches','wellness','family','food','nightlife','lgbtq'],
      bestFor: 'אי נוח עם שדה תעופה, וילות, ספא, חופים מגוונים (Chaweng vs Lamai vs Maenam)',
      bestMonths: 'יולי–ספט וגם ינו–אפר יחסית טובים. אוק–נוב גשום יותר במזרח המפרץ',
      budget: { low: 1400, mid: 3000, high: 7000 },
      mustDos: ['בחרו צד: Chaweng חי, Lamai בינוני, Maenam/Bophut רגוע', 'Fisherman\'s Village ב־Bophut', 'מקדש Big Buddha', 'יום ל־Ang Thong Marine Park'],
      skipIf: 'מחפשים ויב היפי זול — סמוי יותר מלוטש ויקר',
      transit: 'טיסה ישירה / Bangkok Airways. מעבורת מ־Surat Thani. Grab באי.',
      food: 'פירות ים, קוקוס טרי, מסעדות בינלאומיות ב־Chaweng. נסו שוק לילה.'
    },
    {
      id: 'phangan', name: 'Koh Phangan', he: 'קו פנגן', emoji: '🌕',
      vibe: ['מסיבות', 'היפי', 'חופים נסתרים'], interests: ['nightlife','beaches','wellness','nature','adventure'],
      bestFor: 'Full Moon Party ב־Haad Rin — או החופים השקטים בצפון/מערב שרוב האנשים מפספסים',
      bestMonths: 'כמו סמוי. בדקו תאריך ירח מלא אם בא לכם (או לברוח)',
      budget: { low: 1000, mid: 2200, high: 4500 },
      mustDos: ['Full Moon / Half Moon — רק אם בא לכם', 'Than Sadet / Bottle Beach לשקט', 'יוגה וספא באזור האיים הצפוניים', 'סקוטר מסביב לאי (זהירות בכבישים)'],
      skipIf: 'אתם שונאים מסיבות — עדיין אפשר, פשוט תגורו רחוק מ־Haad Rin',
      transit: 'מעבורת מ־Samui או Lomprayah מ־Hua Hin/Bangkok corridor. Pier ראשי: Thong Sala.',
      food: 'מיקס היפי־בריא + מסיבות. שייקים, vegan cafes, ברבקיו על החוף.'
    },
    {
      id: 'tao', name: 'Koh Tao', he: 'קו טאו', emoji: '🤿',
      vibe: ['צלילה', 'קז׳ואל', 'אי קטן'], interests: ['adventure','beaches','nightlife','nature'],
      bestFor: 'קורסי PADI זולים ואיכותיים, סנורקל מצוין, ויב backpacker',
      bestMonths: 'יולי–ספט ומר–אפר. גלים חזקים בעונות מעבר',
      budget: { low: 1100, mid: 2200, high: 4000 },
      mustDos: ['קורס צלילה Open Water', 'Sairee Beach בשקיעה', 'Viewpoint / John-Suwan', 'סנורקל ב־Shark Bay (כרישים שחורים קטנים — לא מפחידים)'],
      skipIf: 'אין עניין במים — האי קטן ויש פחות אטרקציות יבשתיות',
      transit: 'מעבורת מ־Samui/Phangan או Lomprayah. נמל Mae Haad.',
      food: 'אוכל backpacker טוב ב־Sairee. מחירים בינוניים לאי קטן.'
    },
    {
      id: 'lanta', name: 'Koh Lanta', he: 'קו לנטה', emoji: '🌅',
      vibe: ['רגוע', 'משפחות', 'שקיעות'], interests: ['beaches','family','wellness','nature','photo'],
      bestFor: 'חופים ארוכים ורגועים, שקיעות מטורפות, פחות המונים מפוקט',
      bestMonths: 'נוב–אפר. בעונת גשם חלק מהמקומות נסגרים',
      budget: { low: 1100, mid: 2200, high: 4000 },
      mustDos: ['Long Beach / Klong Nin', 'שקיעה ב־Lighthouse בקצה הדרומי', 'Old Town בצד המזרחי', 'טיול לאיי National Park'],
      skipIf: 'רוצים אקשן ומסיבות — זה אי לצ׳יל',
      transit: 'מיניוואן + מעבורת מקרבי / פוקט. השכירו סקוטר.',
      food: 'מסעדות שקיעה, פירות ים, אווירה רגועה. נסו את ה־walking street בעונה.'
    },
    {
      id: 'huahin', name: 'Hua Hin', he: 'הואה הין', emoji: '👑',
      vibe: ['מלכותי', 'נוח', 'קרוב לבנגקוק'], interests: ['beaches','food','family','wellness'],
      bestFor: 'חופשת חוף בלי טיסה ארוכה, שווקים, ויב תאי מקומי יותר',
      bestMonths: 'נוב–פבר. חם מאוד בקיץ',
      budget: { low: 1200, mid: 2500, high: 5000 },
      mustDos: ['Cicada / Night Market', 'חוף מרכזי + מקדש על הגבעה', 'Khao Takiab', 'יום ל־Khao Sam Roi Yot (פארק לאומי)'],
      skipIf: 'מחפשים אי טרופי בתולי — זה חוף יבשתי מפותח',
      transit: 'רכבת / אוטובוס מבנגקוק ~3–4ש. Grab בעיר.',
      food: 'פירות ים טריים בשוק, אוכל תאי אותנטי יותר ממקומות תיירותיים בדרום.'
    },
    {
      id: 'ayutthaya', name: 'Ayutthaya', he: 'איוטהאיה', emoji: '🏯',
      vibe: ['היסטוריה', 'יום טיול'], interests: ['culture','photo'],
      bestFor: 'עיר הבירה הישנה — הריסות מקדשים, יום טיול מושלם מבנגקוק',
      bestMonths: 'כל השנה; נוב–פבר נעים יותר לאופניים',
      budget: { low: 800, mid: 1500, high: 2500 },
      mustDos: ['Wat Mahathat (ראש בודהה בעץ)', 'Wat Phra Si Sanphet', 'סיור אופניים / טוק־טוק בין האתרים', 'שוק לילה מקומי'],
      skipIf: 'אין לכם לפחות חצי יום מלא — לא שווה לרוץ',
      transit: 'רכבת מבנגקוק ~1.5–2ש. או מיניוואן. יום טיול קל.',
      food: 'roti sai mai מתוק מקומי, אטריות רחוב ליד הריסות.'
    },
    {
      id: 'sukhothai', name: 'Sukhothai', he: 'סוקותאי', emoji: '🛕',
      vibe: ['היסטוריה', 'רגוע'], interests: ['culture','photo','nature'],
      bestFor: 'פארק היסטורי שקט ויפהפה — פחות המונים מאיוטהאיה, זריחות קסומות',
      bestMonths: 'נוב–פבר',
      budget: { low: 800, mid: 1500, high: 2800 },
      mustDos: ['Historical Park באופניים בבוקר', 'Wat Mahathat בשעת זהב', 'מוזיאון Ramkhamhaeng'],
      skipIf: 'מסלול צפוף — אפשר לדלג אם כבר עושים איוטהאיה + צפון מלא',
      transit: 'אוטובוס מ־Chiang Mai או בנגקוק. שדה קטן.',
      food: 'מנות צפוניות־מרכזיות, אווירה מקומית רגועה.'
    },
    {
      id: 'kanchanaburi', name: 'Kanchanaburi', he: 'קנצ׳נבורי', emoji: '🌉',
      vibe: ['היסטוריה', 'נהר', 'טבע'], interests: ['culture','nature','adventure','photo'],
      bestFor: 'גשר נהר קוואי, מפלי Erawan, לג׳ונגל קרוב לבנגקוק',
      bestMonths: 'נוב–פבר. מפלים מלאים יותר אחרי גשם',
      budget: { low: 900, mid: 1800, high: 3200 },
      mustDos: ['Erawan Falls (7 קומות — התחילו מוקדם)', 'Death Railway / Bridge on the River Kwai', 'לילה על רפטינג/בקתות נהר', 'מוזיאון המלחמה'],
      skipIf: 'רק יום אחד — Erawan לבד צריך בוקר שלם',
      transit: 'אוטובוס מבנגקוק ~2–3ש. לימי הטבע: ארגנו הסעה למפלים.',
      food: 'דג נהר, אוכל מקומי פשוט וטעים ליד הגשר.'
    },
    {
      id: 'khaosok', name: 'Khao Sok', he: 'קאו סוק', emoji: '🐊',
      vibe: ['ג׳ונגל', 'אגם', 'הרפתקה'], interests: ['nature','adventure','photo'],
      bestFor: 'אגם Cheow Lan עם קרסטים דרמטיים, לינה בבית רפסודה, ג׳ונגל עתיק',
      bestMonths: 'דצ–אפר. בעונת גשם חלק מהסירות מוגבלות — אבל ירוק מדהים',
      budget: { low: 1500, mid: 2800, high: 4500 },
      mustDos: ['לילה ב־floating bungalow באגם', 'שייט קאנו / סירה בין הקרסטים', 'טרק קצר בג׳ונגל', 'שחר עם הערפל על האגם'],
      skipIf: 'פחד מחרקים / רוצים מותרות עירוניות',
      transit: 'מיניוואן מ־Surat Thani / קרבי / פוקט. 12Go מועיל. יום שלם למעבר.',
      food: 'ארוחות כלולות לרוב בחבילות האגם. אוכל בסיסי בכפר.'
    },
    {
      id: 'chang', name: 'Koh Chang', he: 'קו צ׳אנג', emoji: '🐘',
      vibe: ['טבע', 'חופים', 'מזרח'], interests: ['beaches','nature','adventure','nightlife'],
      bestFor: 'אי גדול במזרח (ליד קמבודיה), ג׳ונגל + חופים, פחות הייפ מדרום',
      bestMonths: 'נוב–פבר. מאי–אוק גשום מאוד במזרח',
      budget: { low: 1100, mid: 2200, high: 4000 },
      mustDos: ['White Sand / Kai Bae', 'מפלים בפנים האי', 'סנורקל ל־Koh Wai / קרובים', 'West coast בשקיעה'],
      skipIf: 'עונת הגשמים — הרבה מקומות סוגרים',
      transit: 'דרך Trat + מעבורת. טיסות ל־Trat. באנגקוק ~5–6ש כולל מעבורת.',
      food: 'פירות ים, אווירת באקפקר ב־Lonely Beach.'
    },
    {
      id: 'samet', name: 'Koh Samet', he: 'קו סאמט', emoji: '🏖️',
      vibe: ['קרוב', 'סופ״ש', 'חופים'], interests: ['beaches','nightlife','family'],
      bestFor: 'אי קרוב לבנגקוק לסופ״ש / 2–3 ימים בלי לטוס רחוק',
      bestMonths: 'נוב–פבר',
      budget: { low: 1300, mid: 2500, high: 4500 },
      mustDos: ['Sai Kaew Beach', 'שכירות אופנוע מסביב', 'שקיעה בצד המערבי'],
      skipIf: 'טיול ארוך — לא שווה יעד ראשי ל־3 שבועות',
      transit: 'אוטובוס ל־Ban Phe + מעבורת קצרה. יום שלם מבנגקוק הלוך־חזור אפשרי אבל עמוס.',
      food: 'מסעדות חוף תיירותיות. מחירים גבוהים יחסית למיקום.'
    },
    {
      id: 'isaan', name: 'Isaan', he: 'איסאן (צפון־מזרח)', emoji: '🌾',
      vibe: ['אותנטי', 'אוכל', 'פחות תיירים'], interests: ['food','culture','photo','nature'],
      bestFor: 'תאילנד האמיתית — אוכל איסאן חריף, אתרים כמו Pha Taem, פחות תיירים',
      bestMonths: 'נוב–פבר',
      budget: { low: 700, mid: 1400, high: 2500 },
      mustDos: ['Som tum + larb + sticky rice אותנטיים', 'Khmer ruins (Phimai / Phanom Rung)', 'נהר Mekong באזורים מסוימים'],
      skipIf: 'טיול ראשון קצר — שמרו לביקור שני',
      transit: 'רכבות ואוטובוסים מבנגקוק. תשתית תיירותית דלילה יותר.',
      food: 'הבית של cuisine איסאן — חובה לחובבי אוכל אמיצים.'
    }
  ],

  activities: {
    bangkok: ['סיור אוכל רחוב בלילה', 'BTS ל־Siam + קניות', 'Wat Arun + שקיעה', 'מסאג׳ תאי 60–90 דק׳', 'Chatuchak (סופ״ש)', 'שייט Chao Phraya', 'רובע Ari — קפה וברים', 'מוזיאון / Jim Thompson House'],
    chiangmai: ['Old Town ברגל', 'Doi Suthep', 'Sunday Walking Street', 'יום אתיקה עם פילים', 'קפה ב־Nimman', 'שיעור בישול תאי', 'טרק הרים חצי יום', 'מקדשים בצפון העיר'],
    chiangrai: ['White Temple', 'Blue Temple', 'Golden Triangle', 'סיור קפה/תה'],
    pai: ['Pai Canyon', 'מפלים', 'שוק לילה', 'ספא / יוגה', 'סקוטר לכפרים'],
    phuket: ['יום חוף (Kata/Karon/Nai Harn)', 'Old Phuket Town', 'טיול איים', 'ספא', 'שוק לילה', 'צלילה/סנורקל'],
    krabi: ['4 Islands tour', 'Hong Island', 'Tiger Cave Temple', 'חוף Ao Nang', 'קיאקים במנגרובים'],
    railay: ['Phra Nang Beach', 'שיעור טיפוס', 'Viewpoint', 'שקיעה West Railay'],
    phiphi: ['סנורקל יום', 'Viewpoint', 'Long Beach', 'Maya Bay (לפי כללים)'],
    samui: ['חוף לפי אזור', 'Fisherman\'s Village', 'Big Buddha', 'Ang Thong day trip', 'ספא'],
    phangan: ['חוף שקט בצפון', 'Full Moon Party', 'יוגה', 'סקוטר מסביב לאי', 'מפלים'],
    tao: ['קורס צלילה', 'סנורקל', 'Sairee Beach', 'Viewpoint'],
    lanta: ['Long Beach', 'Lighthouse sunset', 'Old Town', 'יום איים'],
    huahin: ['Night Market', 'חוף', 'Khao Takiab', 'יום לאומי פארק'],
    ayutthaya: ['סיור אופניים בפארק', 'Wat Mahathat', 'טוק־טוק בין מקדשים'],
    sukhothai: ['Historical Park באופניים', 'זריחה במקדשים'],
    kanchanaburi: ['Erawan Falls', 'גשר נהר קוואי', 'Death Railway', 'לינה על הנהר'],
    khaosok: ['שייט אגם Cheow Lan', 'לילה ב־floating bungalow', 'טרק ג׳ונגל'],
    chang: ['חוף מערבי', 'מפלים', 'סנורקל לאיים קרובים'],
    samet: ['Sai Kaew', 'סקוטר מסביב', 'שקיעה'],
    isaan: ['אוכל איסאן', 'אתרי חמר', 'שוק מקומי']
  },

  sampleItineraries: [
    {
      id: 'classic7', name: '7 ימים קלאסי', he: 'בנגקוק ← צ׳יאנג מאי',
      days: [
        { region: 'bangkok', note: 'הגעה, צ׳יינהטאון בלילה' },
        { region: 'bangkok', note: 'מקדשים + Chao Phraya' },
        { region: 'bangkok', note: 'Ari / Chatuchak / מסאג׳' },
        { region: 'chiangmai', note: 'טיסה צפונה, Old Town' },
        { region: 'chiangmai', note: 'Doi Suthep + שוק' },
        { region: 'chiangmai', note: 'יום טבע / פילים אתי' },
        { region: 'chiangmai', note: 'קפה + טיסת חזרה / המשך' }
      ]
    },
    {
      id: 'northbeach10', name: '10 ימים צפון + חוף', he: 'בנגקוק ← צפון ← סמוי',
      days: [
        { region: 'bangkok', note: 'הגעה ואוכל' },
        { region: 'bangkok', note: 'מקדשים ושווקים' },
        { region: 'chiangmai', note: 'טיסה, Old Town' },
        { region: 'chiangmai', note: 'הרים ותרבות' },
        { region: 'chiangmai', note: 'קפה ויום חופשי' },
        { region: 'samui', note: 'טיסה דרומה (יום מעבר)' },
        { region: 'samui', note: 'חוף וספא' },
        { region: 'samui', note: 'Fisherman\'s Village' },
        { region: 'samui', note: 'Ang Thong או צ׳יל' },
        { region: 'samui', note: 'יציאה' }
      ]
    },
    {
      id: 'islands14', name: '14 ימים איים', he: 'פוקט ← קרבי ← איים',
      days: [
        { region: 'phuket', note: 'הגעה, חוף רגוע (לא Patong)' },
        { region: 'phuket', note: 'Old Town + חוף' },
        { region: 'phiphi', note: 'מעבורת, סנורקל' },
        { region: 'phiphi', note: 'Viewpoint / Long Beach' },
        { region: 'krabi', note: 'מעבר ל־Ao Nang' },
        { region: 'krabi', note: '4 Islands' },
        { region: 'railay', note: 'לונגטייל לריילי' },
        { region: 'railay', note: 'טיפוס / Phra Nang' },
        { region: 'lanta', note: 'מעבר לקו לנטה' },
        { region: 'lanta', note: 'חופים ושקיעות' },
        { region: 'lanta', note: 'Old Town / צ׳יל' },
        { region: 'lanta', note: 'יום איים' },
        { region: 'krabi', note: 'חזרה לקרבי' },
        { region: 'krabi', note: 'יציאה משדה קרבי' }
      ]
    },
    {
      id: 'grand21', name: '21 ימים גרנד טור', he: 'בנגקוק ← צפון ← איים',
      days: [
        { region: 'bangkok', note: 'הגעה' }, { region: 'bangkok', note: 'עיר ואוכל' },
        { region: 'ayutthaya', note: 'יום טיול הריסות' },
        { region: 'kanchanaburi', note: 'Erawan + גשר' }, { region: 'kanchanaburi', note: 'טבע' },
        { region: 'bangkok', note: 'לילה וטיסה צפונה' },
        { region: 'chiangmai', note: 'Old Town' }, { region: 'chiangmai', note: 'Doi Suthep' }, { region: 'chiangmai', note: 'טבע' },
        { region: 'pai', note: 'מיניוואן לפאי' }, { region: 'pai', note: 'קניון ומפלים' },
        { region: 'chiangmai', note: 'חזרה וטיסה דרומה' },
        { region: 'khaosok', note: 'ג׳ונגל ואגם' }, { region: 'khaosok', note: 'floating bungalow' },
        { region: 'krabi', note: 'מעבר לחוף' }, { region: 'railay', note: 'צוקים' },
        { region: 'phuket', note: 'מעבר' }, { region: 'phuket', note: 'חוף' },
        { region: 'phuket', note: 'צ׳יל' }, { region: 'phuket', note: 'יציאה' }
      ]
    },
    {
      id: 'foodie', name: 'Foodie: בנגקוק + צ׳יאנג מאי', he: '8 ימים של אוכל',
      days: [
        { region: 'bangkok', note: 'Yaowarat בלילה' },
        { region: 'bangkok', note: 'שיעור בישול + שוק' },
        { region: 'bangkok', note: 'Ari + Thonglor food crawl' },
        { region: 'bangkok', note: 'Boat noodles + street food' },
        { region: 'chiangmai', note: 'טיסה, khao soi tour' },
        { region: 'chiangmai', note: 'Warorot + Sunday market' },
        { region: 'chiangmai', note: 'שיעור בישול צפוני' },
        { region: 'chiangmai', note: 'קפה ספשלטי + יציאה' }
      ]
    },
    {
      id: 'party_chill', name: '12 ימים מסיבות + צ׳יל', he: 'סמוי ← פנגן ← טאו',
      days: [
        { region: 'samui', note: 'הגעה, חוף רגוע' }, { region: 'samui', note: 'Fisherman\'s Village' },
        { region: 'phangan', note: 'מעבורת' }, { region: 'phangan', note: 'חוף שקט' },
        { region: 'phangan', note: 'Full Moon / מסיבה' }, { region: 'phangan', note: 'התאוששות + יוגה' },
        { region: 'tao', note: 'מעבורת לטאו' }, { region: 'tao', note: 'צלילה יום 1' },
        { region: 'tao', note: 'צלילה יום 2' }, { region: 'tao', note: 'Sairee צ׳יל' },
        { region: 'samui', note: 'חזרה' }, { region: 'samui', note: 'יציאה' }
      ]
    }
  ],

  packingItems: [
    { id: 'passport', he: 'דרכון + צילום / ענן', cat: 'מסמכים' },
    { id: 'insurance', he: 'ביטוח נסיעות (כולל צלילה אם רלוונטי)', cat: 'מסמכים' },
    { id: 'adapter', he: 'מתאם Type A/B/C (תאילנד Type A/B/O)', cat: 'אלקטרוניקה' },
    { id: 'powerbank', he: 'סוללה ניידת', cat: 'אלקטרוניקה' },
    { id: 'sunblock', he: 'מסנן קרינה SPF50 (נמכר גם שם, יקר יותר)', cat: 'בריאות' },
    { id: 'mosquito', he: 'דוחה יתושים (DEET / picaridin)', cat: 'בריאות' },
    { id: 'meds', he: 'תרופות אישיות + אלרגיות / בטן', cat: 'בריאות' },
    { id: 'modest', he: 'בגדים לכיסוי כתפיים וברכיים למקדשים', cat: 'בגדים' },
    { id: 'sandals', he: 'סנדלים נוחים + נעלי הליכה', cat: 'בגדים' },
    { id: 'rain', he: 'פונצ׳ו / מטרייה קלה (עונת גשם)', cat: 'בגדים' },
    { id: 'drybag', he: 'תיק יבש לסירות ולונגטייל', cat: 'ציוד' },
    { id: 'lock', he: 'מנעול קטן לתיק / לוקר', cat: 'ציוד' },
    { id: 'reef', he: 'קרם ידידותי לשונית (אם צוללים)', cat: 'בריאות' },
    { id: 'cash', he: 'קצת מזומן USD/EUR להמרה ראשונית', cat: 'כסף' },
    { id: 'card', he: 'כרטיס עם משיכות ATM זולות (אין עמלת חו״ל)', cat: 'כסף' }
  ],

  foodMustTries: [
    { he: 'Pad Thai', note: 'Thip Samai בבנגקוק — הקלאסיקה' },
    { he: 'Khao Soi', note: 'צ׳יאנג מאי — קארי קוקוס עם אטריות ביצה' },
    { he: 'Som Tum', note: 'סלט פפאיה חריף — בקשו "mai ped" אם לא חריף' },
    { he: 'Mango Sticky Rice', note: 'בעונת מנגו (בערך מר–יונ) — שמיים' },
    { he: 'Boat Noodles', note: 'אטריות בסירות קטנות / קערות קטנות — הזמינו כמה' },
    { he: 'Moo Ping', note: 'שיפודים על הגריל בבוקר עם sticky rice' },
    { he: 'Massaman Curry', note: 'עדין יחסית, עם תפוחי אדמה ובשר' },
    { he: 'Sai Ua', note: 'נקניקיית צפון מתובלת — עם נאם פריק' },
    { he: 'Fresh coconut', note: 'קוקוס ירוק קר בכל חוף' },
    { he: 'Thai iced tea / coffee', note: 'מתוק וחזק — cha yen' }
  ],

  apps: [
    { id: 'grab', name: 'Grab', he: 'Grab', cat: 'rides', icon: '🚗',
      when: 'מונית, אוכל, שליחויות — האפליקציה הכי חשובה בתאילנד',
      tips: 'הזמינו תמיד דרך האפליקציה (מחיר קבוע). בנמלים לפעמים צריך לעמוד בנקודת Grab. טיפ: שמרו כתובות במלונית באנגלית + פינ במפה.',
      urls: [{ label: 'אתר', url: 'https://www.grab.com/th/en/' }, { label: 'App Store', url: 'https://apps.apple.com/app/grab/id647268330' }, { label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.grabtaxi.passenger' }] },
    { id: 'bolt', name: 'Bolt', he: 'Bolt', cat: 'rides', icon: '⚡',
      when: 'חלופה ל־Grab — לפעמים זול יותר או יותר רכבים באזורים מסוימים',
      tips: 'השוו מחיר מול Grab לפני נסיעה. פחות נפוץ באיים קטנים.',
      urls: [{ label: 'אתר', url: 'https://bolt.eu/' }, { label: 'הורדה', url: 'https://bolt.eu/en/download/' }] },
    { id: 'indrive', name: 'inDrive', he: 'inDrive', cat: 'rides', icon: '💬',
      when: 'כשרוצים להתמקח על מחיר הנסיעה',
      tips: 'מתאים לנסיעות ארוכות יותר. בדקו דירוג נהג. לא תחליף מלא ל־Grab ליום־יום.',
      urls: [{ label: 'אתר', url: 'https://indrive.com/' }] },
    { id: 'taxi-tips', name: 'Taxi & Tuk-tuk', he: 'מוניות וטוק־טוק', cat: 'rides', icon: '🚕',
      when: 'כשאין Grab / נסיעה קצרה תיירותית',
      tips: 'מונית: דרשו מונה (meter). טוק־טוק: קבעו מחיר לפני. מ־BKK airport העדיפו Airport Rail Link / Grab / מונית רשמית בתור. הימנעו מ־"המקדש סגור, אקח אותך לשוק חברים".',
      urls: [] },
    { id: 'klook', name: 'Klook', he: 'Klook', cat: 'activities', icon: '🎟️',
      when: 'טיולי יום, מעבורות, כרטיסים, כרטיסי SIM',
      tips: 'מצוין ל־Phi Phi, Ang Thong, צלילה. קראו ביטולים. לפעמים Agoda/Klook עדיפים לפי המבצע.',
      urls: [{ label: 'Klook', url: 'https://www.klook.com/' }] },
    { id: 'getyourguide', name: 'GetYourGuide', he: 'GetYourGuide', cat: 'activities', icon: '🧭',
      when: 'סיורים מודרכים וחוויות עם ביטול גמיש',
      tips: 'טוב לבנגקוק וצפון. השוו מול Klook לאותו סיור.',
      urls: [{ label: 'GetYourGuide', url: 'https://www.getyourguide.com/' }] },
    { id: 'tripadvisor', name: 'TripAdvisor Experiences', he: 'TripAdvisor', cat: 'activities', icon: '🦉',
      when: 'השראה + הזמנת חוויות אחרי קריאת ביקורות',
      tips: 'אל תסמכו רק על כוכבים — קראו ביקורות שליליות אחרונות. טוב לתכנון, פחות לזמינות last-minute.',
      urls: [{ label: 'Experiences', url: 'https://www.tripadvisor.com/Attractions' }] },
    { id: 'viator', name: 'Viator', he: 'Viator', cat: 'activities', icon: '🚌',
      when: 'טיולים מאורגנים (שייך ל־TripAdvisor)',
      tips: 'דומה ל־GYG. בדקו מה כלול (ארוחות, העברות).',
      urls: [{ label: 'Viator', url: 'https://www.viator.com/' }] },
    { id: 'wantogo', name: 'Day tours', he: 'טיולי יום מקומיים', cat: 'activities', icon: '🏝️',
      when: 'הזמנה דרך מלונית / דוכן בנמל / Wantogo וכדומה',
      tips: 'בקרבי/פוקט דוכני 4 Islands ו־Hong Island בכל פינה. השוו מחיר וגודל קבוצה. הזמן מוקדם בעונה.',
      urls: [{ label: 'Klook day trips', url: 'https://www.klook.com/en-US/experiences/' }] },
    { id: 'booking', name: 'Booking.com', he: 'Booking.com', cat: 'stays', icon: '🏨',
      when: 'מלונות עם ביטול חינם וסינון חזק',
      tips: 'סננו לפי מיקום במפה (לא רק ציון). בתאילנד Agoda לפעמים זול יותר — תמיד השוו.',
      urls: [{ label: 'Booking', url: 'https://www.booking.com/' }] },
    { id: 'agoda', name: 'Agoda', he: 'Agoda', cat: 'stays', icon: '🛏️',
      when: 'לעיתים קרובות הזול ביותר בתאילנד ודרום־מזרח אסיה',
      tips: 'חובה להשוות מול Booking. שימו לב למדיניות ביטול. אפליקציה טובה למבצעי last minute.',
      urls: [{ label: 'Agoda', url: 'https://www.agoda.com/' }] },
    { id: 'airbnb', name: 'Airbnb', he: 'Airbnb', cat: 'stays', icon: '🏡',
      when: 'וילות, שהייה ארוכה, מטבח',
      tips: 'בדקו רישום חוקי ותקשורת עם המארח. באזורים תיירותיים מלונות לפעמים משתלמים יותר.',
      urls: [{ label: 'Airbnb', url: 'https://www.airbnb.com/' }] },
    { id: 'hotels', name: 'Hotels.com', he: 'Hotels.com', cat: 'stays', icon: '⭐',
      when: 'לילות חינם אחרי מספר הזמנות',
      tips: 'שוו תמיד — לא תמיד הכי זול בתאילנד.',
      urls: [{ label: 'Hotels.com', url: 'https://www.hotels.com/' }] },
    { id: '12go', name: '12Go Asia', he: '12Go', cat: 'transport', icon: '🎫',
      when: 'רכבות, אוטובוסים, מעבורות, צירופים',
      tips: 'הכלי הכי שימושי לתכנון מעברים. יש עמלת שירות — לפעמים זול יותר בקופה, אבל 12Go חוסך כאב ראש. שמרו PDF/הזמנה אופליין.',
      urls: [{ label: '12Go', url: 'https://12go.asia/' }] },
    { id: 'bahtbus', name: 'Baht buses / Songthaew', he: 'בוהט באס / סונגטאו', cat: 'transport', icon: '🚐',
      when: 'תחבורה מקומית זולה באיים ובערי צפון',
      tips: 'בפוקט: baht bus אדום לאורך החופים. בצ׳יאנג מאי: songthaew אדום — קבעו מחיר לפני או שימו לב שמקומיים משלמים פחות. אין אפליקציה — זו מציאות ברחוב.',
      urls: [] },
    { id: 'lomprayah', name: 'Lomprayah / Ferries', he: 'מעבורות (Lomprayah וכו\')', cat: 'transport', icon: '⛴️',
      when: 'סמוי–פנגן–טאו, ולפעמים מהיבשה',
      tips: 'Lomprayah אמינה יחסית ל־catamaran. בעונת גשם ייתכנו ביטולים — אל תתכננו טיסה צמודה אחרי מעבורת. הזמינו ב־12Go או באתר.',
      urls: [{ label: 'Lomprayah', url: 'https://www.lomprayah.com/' }, { label: '12Go ferries', url: 'https://12go.asia/' }] },
    { id: 'railway', name: 'Thai Railways', he: 'רכבות תאילנד', cat: 'transport', icon: '🚆',
      when: 'בנגקוק↔צ׳יאנג מאי לילה, איוטהאיה, מסלולים נופיים',
      tips: 'הזמינו מראש בעונה באתר DRT / 12Go. מחלקה 2 מזגן נוחה לרוב המטיילים. הגיעו מוקדם לתחנה.',
      urls: [{ label: 'הזמנת רכבות', url: 'https://www.railway.co.th/' }, { label: '12Go trains', url: 'https://12go.asia/' }] },
    { id: 'airasia', name: 'AirAsia / Bangkok Airways', he: 'טיסות פנימיות', cat: 'transport', icon: '✈️',
      when: 'בנגקוק↔פוקט/קרבי/סמוי/צ׳יאנג מאי',
      tips: 'AirAsia זולה אך הקפדה על משקל. Bangkok Airways נוחה יותר (סמוי) עם lounge. טיסו עם מרווח אחרי מעבורות.',
      urls: [{ label: 'AirAsia', url: 'https://www.airasia.com/' }, { label: 'Bangkok Airways', url: 'https://www.bangkokair.com/' }] },
    { id: 'gmaps', name: 'Google Maps', he: 'Google Maps', cat: 'maps', icon: '🗺️',
      when: 'ניווט יומיומי, תחבורה ציבורית בבנגקוק, שמירת מקומות',
      tips: 'הורידו אזורים אופליין. שמרו PIN של המלון בעברית/אנגלית. BTS/MRT מופיעים טוב בבנגקוק.',
      urls: [{ label: 'Google Maps', url: 'https://maps.google.com/' }] },
    { id: 'applemaps', name: 'Apple Maps', he: 'Apple Maps', cat: 'maps', icon: '🍎',
      when: 'משתמשי iPhone — ניווט בסיסי',
      tips: 'בתאילנד Google Maps עדיין מדויק יותר לתחבורה ותחבורה ציבורית. השתמשו כגיבוי.',
      urls: [] },
    { id: 'mapsme', name: 'Maps.me', he: 'Maps.me', cat: 'maps', icon: '📴',
      when: 'ניווט אופליין מלא בלי קליטה',
      tips: 'הורידו מראש את אזור תאילנד. מעולה באיים ובטרקים. לא מחליף Grab להזמנת נסיעות.',
      urls: [{ label: 'Maps.me', url: 'https://maps.me/' }] },
    { id: 'line', name: 'LINE', he: 'LINE', cat: 'pay', icon: '💚',
      when: 'חובה — המקומיים, מלונות, סוכנים וחנויות מתקשרים ב־LINE',
      tips: 'התקינו לפני הנסיעה. הרבה מאשרי סירות/טיולים ישלחו מיקום ב־LINE. זה ה־WhatsApp של תאילנד.',
      urls: [{ label: 'LINE', url: 'https://line.me/' }] },
    { id: 'promptpay', name: 'PromptPay', he: 'PromptPay', cat: 'pay', icon: 'QR',
      when: 'תשלום QR בכל מקום — שווקים, מסעדות, מוניות לפעמים',
      tips: 'תיירים בדרך כלל משלמים במזומן/כרטיס. אם יש חשבון תאי — PromptPay שולט. אחרת: מזומן קטן + כרטיס.',
      urls: [] },
    { id: 'wise', name: 'Wise', he: 'Wise', cat: 'pay', icon: '💱',
      when: 'המרת כסף ושליחה בשער טוב',
      tips: 'כרטיס Wise / חשבון רב־מטבע חוסך עמלות. בדקו משיכת ATM מול כרטיס ישראלי עם החזרי עמלות.',
      urls: [{ label: 'Wise', url: 'https://wise.com/' }] },
    { id: 'revolut', name: 'Revolut', he: 'Revolut', cat: 'pay', icon: '💳',
      when: 'תשלומים והמרות בנסיעות',
      tips: 'דומה ל־Wise מבחינת נוחות. בדקו מגבלות סוף שבוע על שערים. תמיד גובו עם כרטיס נוסף.',
      urls: [{ label: 'Revolut', url: 'https://www.revolut.com/' }] },
    { id: 'grabfood', name: 'GrabFood', he: 'GrabFood', cat: 'food', icon: '🥡',
      when: 'משלוחי אוכל — במיוחד בימי גשם / אחרי מסיבה / עם ילדים',
      tips: 'תפריטים באנגלית לרוב. בדקו מינימום הזמנה ודמי משלוח. באיים קטנים הכיסוי חלש.',
      urls: [{ label: 'Grab Food', url: 'https://www.grab.com/th/en/food/' }] },
    { id: 'foodpanda', name: 'Foodpanda', he: 'Foodpanda', cat: 'food', icon: '🐼',
      when: 'חלופה ל־GrabFood באזורים מסוימים',
      tips: 'השוו זמני משלוח. בבנגקוק שניהם עובדים טוב.',
      urls: [{ label: 'Foodpanda', url: 'https://www.foodpanda.co.th/' }] },
    { id: 'streetfood', name: 'Street food', he: 'אוכל רחוב — מדריך שטח', cat: 'food', icon: '🍜',
      when: 'תמיד — זה לב החוויה',
      tips: 'עקבו אחרי תורים של מקומיים. שתפו לב למחזור שמן. מים בבקבוק סגור. "mai sai nam pla" / רמת חריפות: "mai ped". הימנעו ממקומות ריקים לגמרי בתיירות כבדה עם תפריט מנופח.',
      urls: [] },
    { id: 'tripcom', name: 'Trip.com', he: 'Trip.com', cat: 'other', icon: '🌐',
      when: 'טיסות + מלונות + אטרקציות בחבילה',
      tips: 'לפעמים מבצעים טובים על טיסות פנימיות. קראו תנאי ביטול.',
      urls: [{ label: 'Trip.com', url: 'https://www.trip.com/' }] },
    { id: 'rome2rio', name: 'Rome2Rio', he: 'Rome2Rio', cat: 'other', icon: '🔀',
      when: 'להבין איך מגיעים מ־A ל־B (רעיון מסלול)',
      tips: 'מעולה להשראה — לא תמיד המחיר/לו״ז מדויקים. אשרו ב־12Go או באתר הרשמי לפני הזמנה.',
      urls: [{ label: 'Rome2Rio', url: 'https://www.rome2rio.com/' }] },
    { id: 'weather', name: 'Weather', he: 'מזג אוויר', cat: 'other', icon: '🌦️',
      when: 'לפני מעבורות וטיולי איים',
      tips: 'השתמשו ב־Windy לגלים ורוח. בעונת גשם בדקו בוקר־של־מעבורת. אפליקציית מזג אוויר רגילה + Windy.',
      urls: [{ label: 'Windy', url: 'https://www.windy.com/' }, { label: 'Thai weather', url: 'https://www.tmd.go.th/en' }] }
  ],

  appCategories: [
    { id: 'all', he: 'הכל' },
    { id: 'rides', he: 'נסיעות ומשלוחים' },
    { id: 'activities', he: 'אטרקציות וכרטיסים' },
    { id: 'stays', he: 'לינה' },
    { id: 'transport', he: 'תחבורה בין ערים' },
    { id: 'maps', he: 'מפות וניווט' },
    { id: 'pay', he: 'הודעות ותשלום' },
    { id: 'food', he: 'אוכל' },
    { id: 'other', he: 'עוד כלים' }
  ]
};
